import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {Window} from 'happy-dom';
import {cinemaDashboard,cinemaMovieLink} from '../public/cinema-dashboard.js';
import {integrateCinemaDashboard} from '../src/cinema-link-runtime.js';
function fixture(api){const window=new Window(),d=window.document,root=d.createElement('main');d.body.append(root);const h=(tag,props={},...children)=>{const el=d.createElement(tag);for(const [k,v] of Object.entries(props)){if(k.startsWith('on'))el.addEventListener(k.slice(2).toLowerCase(),v);else if(k==='class')el.className=v;else if(['hidden','disabled'].includes(k))el[k]=v;else el.setAttribute(k,v);}for(const child of children.flat())if(child!=null)el.append(typeof child==='object'?child:d.createTextNode(String(child)));return el;};cinemaDashboard(root,{h,raw:x=>x,t:x=>x,api,data:{settings:{community:{}},communityModules:[],commands:[]}});return {root,window,input:root.querySelector('input[type=url]'),button:root.querySelector('button')};}
const flush=()=>new Promise(r=>setImmediate(r));
test('Cinema page is usable when the legacy community catalog has no Cinema module',()=>{const {root}=fixture(()=>{});assert.match(root.textContent,/Kurd Cinema movie link/);assert.match(root.textContent,/Join a Discord voice channel/);assert.equal(root.querySelector('input[type=url]').value,'');});
test('dashboard rejects unrelated URLs before making requests',async()=>{let calls=0;const {input,button,root}=fixture(()=>{calls++;});input.value='https://evil.test/movie';button.click();await flush();assert.equal(calls,0);assert.match(root.textContent,/Enter a Kurd Cinema movie link/);assert.equal(cinemaMovieLink('https://kurdcinama.com/online.aspx?movieid=1&movieid=2'),null);});
test('movie inspection renders actual servers and checks selected server without saving settings',async()=>{const paths=[],{root,input,button}=fixture(async p=>{paths.push(p);return p.includes('/resolve?')?{title:'Example Movie',servers:[{id:'77512',label:'Stream wish'},{id:'77511',label:'vidmoly'}]}:{embedUrl:'https://vidmoly.org/embed-example.html'};});input.value='https://kurdcinama.com/moves-details.aspx?movieid=19756';button.click();await flush();await flush();assert.match(root.textContent,/Example Movie/);assert.equal(root.querySelectorAll('option').length,2);assert.match(root.textContent,/Player link is available/);assert.ok(paths.every(p=>p.startsWith('/activity/api/kc/')));const select=root.querySelector('select');select.value='77511';select.dispatchEvent(new root.ownerDocument.defaultView.Event('change'));await flush();assert.match(paths.at(-1),/serverId=77511/);assert.equal(root.querySelector('input[readonly]').value,'https://kurdcinama.com/online.aspx?movieid=19756');});
test('failed provider requests show a useful error and release the check button',async()=>{const {root,input,button}=fixture(async()=>{throw Error('Provider temporarily unavailable');});input.value='https://kurdcinama.com/online.aspx?movieid=19756';button.click();await flush();assert.match(root.textContent,/Provider temporarily unavailable/);assert.equal(button.disabled,false);});
test('editing the movie link prevents stale async results from rendering',async()=>{let resolve;const {root,input,button}=fixture(()=>new Promise(r=>resolve=r));input.value='https://kurdcinama.com/online.aspx?movieid=19756';button.click();input.value='https://kurdcinama.com/online.aspx?movieid=1';input.dispatchEvent(new root.ownerDocument.defaultView.Event('input'));resolve({title:'Stale Movie',servers:[{id:'1'}]});await flush();assert.doesNotMatch(root.textContent,/Stale Movie/);assert.equal(button.disabled,false);});
test('Cinema route is installed before generic community routing and survives repeated installs',()=>{const source=fs.readFileSync(new URL('../public/app.js',import.meta.url),'utf8'),patched=integrateCinemaDashboard(source);assert.equal(integrateCinemaDashboard(patched),patched);assert.ok(patched.indexOf("page==='community:cinema'")<patched.indexOf("page.startsWith('community:')"));assert.throws(()=>integrateCinemaDashboard('unrecognized runtime'));});
