import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {Collection,PermissionsBitField,PermissionFlagsBits as P} from 'discord.js';
process.env.DATA_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'vex-community-'));
const {validateCommunity,communityDefaults}=await import('../src/community-catalog.js');const {saveSettings,settings,db}=await import('../src/db.js');const {awardXP,rank,cases}=await import('../src/community-store.js');const {safeRole,checkCommunity,moderate,communityInteraction}=await import('../src/community.js');const {deliverFeed}=await import('../src/notifications.js');
const id='123456789012345678',ch='223456789012345678',role='323456789012345678';const g={id,ownerId:'owner',roles:{cache:new Collection()},channels:{cache:new Collection()},members:{me:{id:'bot',roles:{highest:{position:10}},permissions:new PermissionsBitField(P.Administrator)}}};
test('community schema rejects forged fields, unbounded rows and unsafe IDs',()=>{assert.throws(()=>validateCommunity({unknown:{}}));assert.throws(()=>validateCommunity({welcome:{channelId:'https://evil.example'}}));assert.throws(()=>validateCommunity({levels:{xp:100000}}));assert.throws(()=>validateCommunity({responder:{rules:Array(21).fill({})}}));assert.throws(()=>validateCommunity({general:{color:'red;script'}}));assert.equal(communityDefaults().tickets.enabled,false);});
test('member cards accept only safe HTTPS banners and per-card colors',()=>{assert.throws(()=>validateCommunity({welcome:{imageUrl:'javascript:alert(1)'}}));assert.throws(()=>validateCommunity({goodbye:{imageUrl:'http://example.com/x.png'}}));assert.throws(()=>validateCommunity({welcome:{color:'invalid'}}));assert.equal(validateCommunity({welcome:{imageUrl:'https://example.com/hello.png'}}).welcome.imageUrl,'https://example.com/hello.png');assert.equal(communityDefaults().goodbye.color,'#8270f5');});
test('community partial save preserves sibling modules and separates servers',()=>{saveSettings(id,{community:{welcome:{title:'Hello'},levels:{xp:30}}});saveSettings(id,{community:{welcome:{enabled:false}}});assert.equal(settings(id).community.welcome.title,'Hello');assert.equal(settings(id).community.levels.xp,30);assert.equal(settings('other').community.levels.xp,15);});
test('XP rejects repeated content, respects cooldown and computes milestones',()=>{assert.equal(awardXP(id,'member','hello world',60,30,100000).level,0);assert.equal(awardXP(id,'member','different content',60,30,110000),null);assert.equal(awardXP(id,'member','HELLO WORLD',60,30,140000),null);assert.equal(awardXP(id,'member','different content',60,30,150000).level,1);assert.equal(rank(id,'member').xp,120);assert.equal(rank('other','member').xp,0);});
test('assignable roles reject administration, managed roles and bot hierarchy',()=>{const r={id:role,position:1,managed:false,permissions:new PermissionsBitField(0n)};g.roles.cache.set(role,r);assert.equal(safeRole(g,role),r);r.permissions=new PermissionsBitField(P.Administrator);assert.throws(()=>safeRole(g,role));r.permissions=new PermissionsBitField(0n);r.position=10;assert.throws(()=>safeRole(g,role));r.position=1;r.managed=true;assert.throws(()=>safeRole(g,role));r.managed=false;});
test('enabled modules require same-server resources and delivery permission',()=>{assert.throws(()=>checkCommunity(g,{welcome:{enabled:true,channelId:ch}}));g.channels.cache.set(ch,{id:ch,type:0,permissionsFor:()=>({has:()=>false})});assert.throws(()=>checkCommunity(g,{welcome:{enabled:true,channelId:ch}}));g.channels.cache.get(ch).permissionsFor=()=>({has:()=>true});assert.equal(checkCommunity(g,{welcome:{enabled:true,channelId:ch}}).welcome.enabled,true);});
test('moderation rejects missing authority and hierarchy before side effects',async()=>{saveSettings(id,{community:{moderation:{enabled:true}}});let touched=false;const target='423456789012345678';g.members.fetch=async()=>({id:target,roles:{highest:{}},bannable:true,ban:async()=>{touched=true;}});const actor={id:'actor',permissions:new PermissionsBitField(0n),roles:{highest:{comparePositionTo:()=>-1}}};await assert.rejects(moderate(g,actor,{action:'ban',target}));actor.permissions=new PermissionsBitField(P.BanMembers);await assert.rejects(moderate(g,actor,{action:'ban',target}));assert.equal(touched,false);assert.equal(cases(id).length,0);});
test('notification baseline suppresses history and delivery is deduplicated',async()=>{let sent=0;g.channels.cache.get(ch).send=async payload=>{sent++;assert.deepEqual(payload.allowedMentions,{parse:[]});};const f={provider:'youtube',source:'example',channelId:ch},one={id:'one',title:'First',url:'https://youtube.com/watch?v=one'},two={id:'two',title:'New',url:'https://youtube.com/watch?v=two'};assert.equal(await deliverFeed(g,f,[one]),0);assert.equal(await deliverFeed(g,f,[two,one]),1);assert.equal(await deliverFeed(g,f,[two,one]),0);assert.equal(sent,1);});
test('failed notification delivery is retried without losing the item',async()=>{const f={provider:'twitch',source:'example',channelId:ch};await deliverFeed(g,f,[]);const item={id:'live',title:'Live',url:'https://twitch.tv/example'};g.channels.cache.get(ch).send=async()=>{throw Error('Unavailable');};await assert.rejects(deliverFeed(g,f,[item]));g.channels.cache.get(ch).send=async()=>({});assert.equal(await deliverFeed(g,f,[item]),1);});
test('stale self-role menu cannot assign a new privileged role',async()=>{saveSettings(id,{community:{selfroles:{enabled:true,roleIds:[role]}}});let message='';const i={guild:g,guildId:id,customId:'vex:roles:select',values:['923456789012345678'],user:{id:'member'},isStringSelectMenu:()=>true,deferReply:async()=>{},editReply:async x=>{message=x.embeds[0].data.description;}};assert.equal(await communityInteraction(i),true);assert.match(message,/outdated/);});
test('ticket channels are private and repeat requests reuse the open ticket',async()=>{
 const support='523456789012345678',category='623456789012345678',ticket='723456789012345678',user='823456789012345678';g.roles.cache.set(support,{id:support});g.channels.cache.set(category,{id:category,type:4});g.members.fetch=async()=>({id:user,roles:{cache:new Collection()},permissions:new PermissionsBitField(0n)});saveSettings(id,{community:{tickets:{enabled:true,supportRoleId:support,categoryId:category,channelId:ch}}});let created=0,reply='';g.channels.create=async args=>{created++;assert.ok(args.permissionOverwrites.find(x=>x.id===id).deny.includes(P.ViewChannel));assert.ok(args.permissionOverwrites.find(x=>x.id===user).allow.includes(P.ViewChannel));assert.equal(args.parent,category);const c={id:ticket,send:async()=>({})};g.channels.cache.set(ticket,c);return c;};const i={guild:g,guildId:id,user:{id:user,username:'tester'},customId:'vex:ticket:request:technical',fields:{getTextInputValue:key=>key==='subject'?'Need help':'Please help with my settings'},isModalSubmit:()=>true,isStringSelectMenu:()=>false,isButton:()=>false,isChatInputCommand:()=>true,deferReply:async()=>{i.deferred=true;},editReply:async x=>{reply=x.embeds[0].data.description;}};await communityInteraction(i);assert.match(reply,/ready/);await communityInteraction(i);assert.match(reply,/already have an open ticket/);assert.equal(created,1);
});
test.after(()=>{db.close();fs.rmSync(process.env.DATA_DIR,{recursive:true,force:true});});
