import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {EventEmitter} from 'node:events';import {Events,AuditLogEvent,Collection} from 'discord.js';
process.env.DATA_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'vex-logs-'));
const {saveSettings,settings,events,db}=await import('../src/db.js');
const {validatePatch}=await import('../src/catalog.js');
const {logEvents}=await import('../src/log-catalog.js');
const {serverLog,attachServerLogs,auditTypes}=await import('../src/logs.js');
const sent=[];const guild={id:'logs-test',name:'Test',channels:{cache:new Collection([['123456789012345678',{type:0,send:async p=>sent.push(p)}]])}};
const rule={enabled:true,channelId:'123456789012345678',color:'#123abc'};
test('log rules strictly reject unknown IDs, unsafe colors and malformed values',()=>{for(const activityLogs of [{unknown:rule},{message_deleted:{color:'url(x)'}},{message_deleted:{enabled:'true'}},{message_deleted:{channelId:'wrong'}},JSON.parse('{"__proto__":{}}')])assert.throws(()=>validatePatch({activityLogs},'basic'));assert.equal(logEvents.length,new Set(logEvents.map(e=>e.id)).size);});
test('partial per-event changes preserve sibling settings and guild isolation',()=>{saveSettings(guild.id,{activityLogs:{message_deleted:rule,message_edited:{...rule,color:'#ffffff'}}});saveSettings(guild.id,{activityLogs:{message_deleted:{color:'#000000'}}});assert.equal(settings(guild.id).activityLogs.message_deleted.channelId,rule.channelId);assert.equal(settings(guild.id).activityLogs.message_edited.color,'#3498db');assert.equal(settings('other').activityLogs.message_deleted.enabled,false);});
test('enabled events route using their channel and standard severity color; disabled events do nothing',async()=>{await serverLog(guild,'message_deleted',{message:'1'});assert.equal(sent.at(-1).embeds[0].color,0xf39c12);assert.deepEqual(sent.at(-1).allowedMentions,{parse:[]});const n=sent.length;await serverLog(guild,'role_created',{target:'2'});assert.equal(sent.length,n);assert.equal(events('other').length,0);});
test('gateway message edits retain metadata without private message content',async()=>{const emitter=new EventEmitter();attachServerLogs(emitter,{messageLogWaitMs:1});emitter.emit(Events.MessageUpdate,{content:'OLD SECRET'},{guild,content:'NEW SECRET',author:{id:'a'},channelId:'c',id:'m'});await new Promise(r=>setImmediate(r));const row=events(guild.id).find(e=>e.kind==='server_message_edited');assert.ok(row);assert.ok(!JSON.stringify(row).includes('SECRET'));});
test('moderator voice moves use audit actor and count without inventing a target',async()=>{saveSettings(guild.id,{activityLogs:{member_moved_by_moderator:rule}});const emitter=new EventEmitter();attachServerLogs(emitter,{messageLogWaitMs:1});emitter.emit(Events.GuildAuditLogEntryCreate,{action:AuditLogEvent.MemberMove,executorId:'moderator',id:'entry',createdTimestamp:Date.now(),extra:{count:2},changes:[]},guild);await new Promise(r=>setImmediate(r));const row=events(guild.id).find(e=>e.kind==='server_member_moved_by_moderator');assert.equal(row.detail.actor,'moderator');assert.equal(row.detail.count,'2');assert.equal(row.detail.target,undefined);for(const id of auditTypes.values())assert.ok(logEvents.some(e=>e.id===id));});
test('partial deletion uses received author and content, but database retains metadata only',async()=>{
 const emitter=new EventEmitter();attachServerLogs(emitter,{messageLogWaitMs:1});
 const message={guild,id:'cached-message',channelId:'123456789012345678',author:{id:'123456789012345679',displayAvatarURL:()=> 'https://cdn.discordapp.com/avatars/example.png'},content:'visible test message'};
 emitter.emit(Events.MessageCreate,message);await new Promise(r=>setImmediate(r));
 emitter.emit(Events.MessageDelete,{guild,id:message.id,channelId:message.channelId,partial:true});await new Promise(r=>setTimeout(r,20));
 const embed=sent.at(-1).embeds[0];
 assert.equal(embed.fields.find(f=>f.name==='Author').value,'<@123456789012345679>');
 assert.match(embed.fields.find(f=>f.name==='Message').value,/visible test message/);
 assert.match(embed.fields.find(f=>f.name==='Deleted by').value,/Unconfirmed/);
 assert.ok(embed.thumbnail);assert.deepEqual(sent.at(-1).allowedMentions,{parse:[]});
 const row=events(guild.id).find(e=>e.kind==='server_message_deleted'&&e.detail.message===message.id);
 assert.ok(row);assert.ok(!JSON.stringify(row).includes('visible test message'));
});
test('message edits display both versions with the reference field layout',async()=>{
 const emitter=new EventEmitter();attachServerLogs(emitter,{messageLogWaitMs:1});
 const before={guild,id:'edit-message',channelId:'123456789012345678',author:{id:'123456789012345679'},content:'before text'};
 emitter.emit(Events.MessageCreate,before);await new Promise(r=>setImmediate(r));
 emitter.emit(Events.MessageUpdate,{...before,partial:true,content:undefined},{...before,content:'after text'});await new Promise(r=>setImmediate(r));
 const embed=sent.at(-1).embeds[0];
 assert.match(embed.fields.find(f=>f.name==='Before').value,/before text/);
 assert.match(embed.fields.find(f=>f.name==='After').value,/after text/);
 assert.equal(embed.fields.find(f=>f.name==='Member').value,'<@123456789012345679>');
 assert.deepEqual(embed.fields.map(f=>[f.name,f.inline]),[['Member',true],['Channel',true],['Before',false],['After',false]]);
 emitter.emit(Events.MessageDelete,{guild,id:before.id,channelId:before.channelId,partial:true});await new Promise(r=>setTimeout(r,20));
 assert.equal(sent.at(-1).embeds[0].fields.find(f=>f.name==='Message').value,'```\nafter text\n```');
});
test.after(()=>{db.close();fs.rmSync(process.env.DATA_DIR,{recursive:true,force:true});});
