import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {PermissionFlagsBits as P} from 'discord.js';
process.env.DATA_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'vex-workspace-'));
const {settings,setState,db}=await import('../src/db.js');
const {saveVersion,history,revision,canEdit,patchScopes,validateAccess,preferences,savePreferences}=await import('../src/workspace.js');
test('history captures previous values atomically and is isolated by server',()=>{saveVersion('a',{community:{welcome:{title:'First'}}},'owner');saveVersion('a',{community:{welcome:{title:'Second'}}},'owner');const r=history('a')[0];assert.equal(JSON.parse(revision('a',r.id).previous).community.welcome.title,'First');assert.equal(revision('b',r.id),undefined);assert.equal(history('b').length,0);assert.equal(settings('a').community.welcome.title,'Second');});
test('only thirty changes are retained without losing the current settings',()=>{for(let i=0;i<35;i++)saveVersion('a',{community:{welcome:{title:'Revision '+i}}},'owner');assert.equal(history('a').length,30);assert.equal(settings('a').community.welcome.title,'Revision 34');});
test('access limits deny omitted scopes and never grant Discord permission',()=>{const g={id:'a',ownerId:'owner'},m={id:'admin',permissions:{has:p=>p===P.Administrator}};assert.equal(canEdit(g,m,'logs'),true);setState('a','dashboard_access',{admin:['logs']});assert.equal(canEdit(g,m,'logs'),true);assert.equal(canEdit(g,m,'protection'),false);assert.equal(canEdit(g,{...m,permissions:{has:()=>false}},'logs'),false);assert.equal(canEdit(g,{id:'owner'},'protection'),true);assert.deepEqual(patchScopes({community:{},modules:{},activityLogs:{}}),['community','protection','logs']);assert.throws(()=>validateAccess({'123456789012345678':['unknown']}));});
test('personal preferences remain separate by user and server',()=>{savePreferences('a','one',{theme:'gold',favorites:['community:welcome']});assert.equal(preferences('a','one').theme,'gold');assert.equal(preferences('a','two').theme,'violet');assert.equal(preferences('b','one').theme,'violet');assert.throws(()=>savePreferences('a','one',{favorites:['<script>']}));assert.throws(()=>savePreferences('a','one',{theme:'untrusted'}));});
test.after(()=>{db.close();fs.rmSync(process.env.DATA_DIR,{recursive:true,force:true});});
