import crypto from 'node:crypto';
import {PermissionFlagsBits as P} from 'discord.js';
import {db,plan,getState,setState,event} from './db.js';
import {planLimits,hasFeature} from './plan-catalog.js';
import {safeRole} from './community.js';
import {onDomainEvent} from './domain-events.js';
import {backup} from './operations.js';
const types={member_joined:'member',level_reached:'level',security_incident:'incident',message_violation:'incident',join_protection:'incident',ticket_opened:'ticket'};
db.exec('CREATE TABLE IF NOT EXISTS automation_runs(guild TEXT NOT NULL,rule TEXT NOT NULL,event TEXT NOT NULL,status TEXT NOT NULL,at INTEGER NOT NULL,PRIMARY KEY(guild,rule,event));');
export const automationRules=g=>getState(g,'automation-rules',[]);
export function validateAutomations(g,rules,owner){if(!Array.isArray(rules)||rules.length>planLimits(plan(g.id)).automationRules)throw Error('Too many automation rules for this plan');const ids=new Set();return rules.map(r=>{if(!r||typeof r!=='object'||Array.isArray(r)||Object.keys(r).some(k=>!['id','name','enabled','trigger','action','level','channelId','message','roleId','staffId','cooldownSeconds','authorizedBy'].includes(k)))throw Error('Invalid automation rule');if(typeof r.enabled!=='boolean'||typeof r.name!=='string'||!r.name.trim()||r.name.length>80||!['member','level','incident','ticket'].includes(r.trigger)||!['message','role','assign'].includes(r.action))throw Error('Complete the automation');if(['incident','ticket'].includes(r.trigger)&&!hasFeature(plan(g.id),'advancedAutomations'))throw Error('Incident and ticket automations require Ultimate');if(r.action==='role'&&!['member','level'].includes(r.trigger))throw Error('Role rewards require a member or level trigger');if(r.action==='assign'&&(r.trigger!=='ticket'||!hasFeature(plan(g.id),'advancedAutomations')))throw Error('Ticket assignment requires Ultimate');const id=r.id||crypto.randomUUID();if(typeof id!=='string'||!/^[a-zA-Z0-9-]{1,40}$/.test(id)||ids.has(id))throw Error('Invalid automation identifier');ids.add(id);const x={id,name:r.name.trim(),enabled:r.enabled,trigger:r.trigger,action:r.action,authorizedBy:owner,level:r.level??1,cooldownSeconds:r.cooldownSeconds??60};if(!Number.isInteger(x.level)||x.level<1||x.level>1000||!Number.isInteger(x.cooldownSeconds)||x.cooldownSeconds<30||x.cooldownSeconds>86400)throw Error('Invalid automation threshold');if(r.action==='role'){safeRole(g,r.roleId);x.roleId=r.roleId;}if(r.action==='message'){const c=g.channels.cache.get(r.channelId);if(!c||![0,5].includes(c.type)||!c.permissionsFor(g.members.me)?.has([P.ViewChannel,P.SendMessages]))throw Error('Choose an accessible message channel');if(typeof r.message!=='string'||!r.message.trim()||r.message.length>1500)throw Error('Write a message of 1–1500 characters');x.channelId=r.channelId;x.message=r.message;}if(r.action==='assign'){if(typeof r.staffId!=='string'||!/^\d{17,22}$/.test(r.staffId))throw Error('Choose a staff member');x.staffId=r.staffId;}return x;});}
export const saveAutomations=(g,rules,owner)=>{const valid=validateAutomations(g,rules,owner);setState(g.id,'automation-rules',valid);return valid;};
const queues=new Map(),pending=new Map();
export async function runAutomations(client,e){const g=client.guilds.cache.get(e.guild),trigger=types[e.kind];if(!g||!trigger||!hasFeature(plan(g.id),'automations'))return;for(const r of automationRules(g.id).slice(0,planLimits(plan(g.id)).automationRules)){if(!r.enabled||r.authorizedBy!==g.ownerId||r.trigger!==trigger||['incident','ticket'].includes(trigger)&&!hasFeature(plan(g.id),'advancedAutomations'))continue;if(trigger==='level'&&(e.detail.level<r.level||Number(e.detail.previous??0)>=r.level))continue;const target=e.detail.member||e.detail.target||e.detail.actor,key=String(e.id),cool='automation-cooldown:'+r.id+':'+(target||'server');if(getState(g.id,cool,0)>Date.now())continue;const claimed=db.prepare('INSERT OR IGNORE INTO automation_runs VALUES(?,?,?,?,?)').run(g.id,r.id,key,'started',Date.now());if(!claimed.changes)continue;setState(g.id,cool,Date.now()+r.cooldownSeconds*1000);
 try{if(!hasFeature(plan(g.id),'automations'))throw Error('Plan expired');if(r.action==='role'){if(!target)throw Error('Member unavailable');const member=await g.members.fetch({user:target,force:true});if(member.user.bot||member.id===g.ownerId)throw Error('Member cannot receive an automatic reward');if(!hasFeature(plan(g.id),'automations')||r.authorizedBy!==g.ownerId)throw Error('Automation access changed');safeRole(g,r.roleId);if(!member.roles.cache.has(r.roleId))await member.roles.add(r.roleId,'VEX owner-approved automation '+r.id);}else if(r.action==='message'){const c=g.channels.cache.get(r.channelId);if(!c||![0,5].includes(c.type)||!c.permissionsFor(g.members.me)?.has([P.ViewChannel,P.SendMessages]))throw Error('Destination unavailable');const member=g.members.cache.get(target);const content=r.message.replaceAll('{user}',member?.displayName||target||'Member').replaceAll('{server}',g.name).replaceAll('{level}',String(e.detail.level||'')).replaceAll('{event}',e.kind).slice(0,1900);if(!hasFeature(plan(g.id),'automations')||r.authorizedBy!==g.ownerId)throw Error('Automation access changed');await c.send({content,allowedMentions:{parse:[]}});}else if(r.action==='assign'){if(!hasFeature(plan(g.id),'advancedAutomations'))throw Error('Ultimate expired');const {autoAssignTicket}=await import('./tickets.js');if(r.authorizedBy!==g.ownerId)throw Error('Owner changed');await autoAssignTicket(g,e.detail.channel,r.staffId,r.authorizedBy);}db.prepare("UPDATE automation_runs SET status='completed' WHERE guild=? AND rule=? AND event=?").run(g.id,r.id,key);event(g.id,'automation_completed',{rule:r.id,trigger,target});}
 catch(err){db.prepare("UPDATE automation_runs SET status='failed' WHERE guild=? AND rule=? AND event=?").run(g.id,r.id,key);event(g.id,'automation_failed',{rule:r.id,trigger,result:'Check saved rule, plan, staff access and role/channel permissions',code:err.code||err.name});}
 }db.prepare('DELETE FROM automation_runs WHERE at<?').run(Date.now()-90*86400000);}
export function setBackupSchedule(g,enabled,hours,owner){if(typeof enabled!=='boolean'||![24,168].includes(hours))throw Error('Invalid backup schedule');if(enabled&&!hasFeature(plan(g),'scheduledBackup'))throw Error('Scheduled backups require Ultimate');const s={enabled,hours,authorizedBy:owner,nextAt:Date.now()+hours*3600000};setState(g,'backup-schedule',s);return s;}
export async function scheduledBackups(client,now=Date.now()){for(const g of client.guilds.cache.values()){const s=getState(g.id,'backup-schedule');if(!s?.enabled||s.authorizedBy!==g.ownerId||s.nextAt>now||!hasFeature(plan(g.id),'scheduledBackup'))continue;setState(g.id,'backup-schedule',{...s,nextAt:now+s.hours*3600000});try{await backup(g,s.authorizedBy);event(g.id,'scheduled_backup_completed',{actor:s.authorizedBy});}catch(e){event(g.id,'scheduled_backup_failed',{code:e.code||e.name,result:'Check permissions before the next scheduled backup'});}}}
const attached=new WeakSet();
export function attachAutomations(client){if(attached.has(client))return;attached.add(client);client.on('guildMemberAdd',m=>{if(!m.user.bot)event(m.guild.id,'member_joined',{member:m.id});});onDomainEvent(e=>{if(!client.isReady()||(pending.get(e.guild)||0)>=100)return;pending.set(e.guild,(pending.get(e.guild)||0)+1);const before=queues.get(e.guild)||Promise.resolve();const next=before.then(()=>runAutomations(client,e)).catch(err=>console.warn('VEX_AUTOMATION_FAILED',err.code||err.name));queues.set(e.guild,next);void next.finally(()=>{const count=(pending.get(e.guild)||1)-1;if(count)pending.set(e.guild,count);else pending.delete(e.guild);if(queues.get(e.guild)===next)queues.delete(e.guild);});});client.once('clientReady',()=>{let running=false;const poll=async()=>{if(running||!client.isReady())return;running=true;try{await scheduledBackups(client);}finally{running=false;}};const timer=setInterval(()=>void poll().catch(e=>console.warn('VEX_BACKUP_SCHEDULE_FAILED',e.code||e.name)),60000);timer.unref();});}
