import {deferPrivate,respondPrivate} from './interaction-response.js';
import {attachTicketRefresh,handleTicketInteraction,publishTicketPanel} from './tickets.js';
import {welcomePayload} from './welcome.js';
import {Events,PermissionFlagsBits as P,ChannelType,ActionRowBuilder,ButtonBuilder,ButtonStyle,StringSelectMenuBuilder,EmbedBuilder} from 'discord.js';
import {settings,getState,setState,event,db} from './db.js';
import {communityModules,mergeCommunity} from './community-catalog.js';
import {awardXP,rank,leaderboard,count,daily,addCase,cases,tickets} from './community-store.js';
import {env} from './config.js';
export const community=g=>settings(g).community;
const color=g=>parseInt(community(g).general.color.slice(1),16);
export const card=(g,title,description,extra={})=>({embeds:[new EmbedBuilder().setColor(color(g)).setAuthor({name:'VEX · COMMUNITY OS'}).setTitle(String(title||'VEX').slice(0,256)).setDescription(String(description||' ').slice(0,3900)).setFooter({text:community(g).general.footer||'VEX · Community OS'}).setTimestamp()],allowedMentions:{parse:[]},...extra});
const dangerous=P.Administrator|P.ManageGuild|P.ManageRoles|P.ManageChannels|P.BanMembers|P.KickMembers|P.ModerateMembers|P.ManageWebhooks|P.ManageMessages|P.MentionEveryone|P.ManageEvents|P.ManageThreads;
export function safeRole(g,id){const r=g.roles.cache.get(id),me=g.members.me;if(!r||r.id===g.id||r.managed||!me||r.position>=me.roles.highest.position||(r.permissions.bitfield&dangerous)!==0n)throw Error('Choose a non-administrative role below VEX');return r;}
const supportRole=(g,id)=>{const r=g.roles.cache.get(id);if(!r||id===g.id)throw Error('Choose a support role in this server');return r;};
const textChannel=(g,id)=>{const c=g.channels.cache.get(id);if(!c||![0,5].includes(c.type))throw Error('Choose a text channel in this server');if(!c.permissionsFor(g.members.me)?.has([P.ViewChannel,P.SendMessages,P.EmbedLinks]))throw Error('VEX cannot send embeds in this channel');return c;};
const template=(text,m)=>text.replaceAll('{user}',`<@${m.id}>`).replaceAll('{username}',m.user.username).replaceAll('{server}',m.guild.name).replaceAll('{count}',String(m.guild.memberCount));
export function memberCard(g,cfg,m){if(cfg.format)return welcomePayload(g,cfg,m);const message=card(g.id,template(cfg.title,m),template(cfg.message,m));const embed=message.embeds[0];if(cfg.color)embed.setColor(parseInt(cfg.color.slice(1),16));if(cfg.imageUrl)embed.setImage(cfg.imageUrl);return message;}
export function checkCommunity(g,patch){const next=mergeCommunity(community(g.id),patch);
 for(const [id,values]of Object.entries(patch)){const spec=communityModules.find(m=>m.id===id),cfg=next[id];
 const inspect=(fields,values)=>{for(const f of fields){const v=values[f.key];if(f.type==='channel'&&v){const c=g.channels.cache.get(v);if(!c||!f.types.includes(c.type))throw Error('Invalid channel: '+f.label);if(cfg.enabled&&[0,5].includes(c.type))textChannel(g,v);}if(f.type==='role'&&v)(f.key==='supportRoleId'?supportRole:safeRole)(g,v);if(f.type==='roles')for(const id of v||[])safeRole(g,id);if(f.type==='rows')for(const row of v||[])inspect(f.fields,row);}};inspect(spec.fields,cfg);if(id==='welcome'&&cfg.sayHiEnabled&&!cfg.chatChannelId)throw Error('Choose an introduction channel before enabling Say Hi');
 if(cfg.enabled){const required={embeds:['channelId'],welcome:['channelId'],goodbye:['channelId'],selfroles:['channelId'],starboard:['channelId'],tempvoice:['lobbyId','categoryId'],templinks:['channelId'],tickets:['categoryId','channelId','supportRoleId']}[id]||[];for(const key of required)if(!cfg[key])throw Error('Complete required channels and roles before enabling '+spec.name);
 if(id==='welcome'){if(cfg.buttons.some(b=>!b.label||!b.url))throw Error('Complete every welcome link button');if(cfg.fields.some(f=>!f.name||!f.value))throw Error('Complete every welcome information block');if(cfg.thumbnail==='custom'&&!cfg.thumbnailUrl)throw Error('Choose a custom portrait URL');}
 if(['autoroles','selfroles'].includes(id)&&!cfg.roleIds.length)throw Error('Choose at least one role');
 if(id==='responder'&&cfg.rules.some(r=>!r.trigger||!r.response))throw Error('Complete every response rule');
 if(id==='notifications')for(const f of cfg.feeds){if(!f.channelId||!f.source)throw Error('Complete every notification source');const re={youtube:/^UC[A-Za-z0-9_-]{22}$/,twitch:/^[A-Za-z0-9_]{1,25}$/,kick:/^\d{1,20}$/,reddit:/^[A-Za-z0-9_]{2,21}$/}[f.provider];if(!re.test(f.source))throw Error('Invalid source: use YouTube channel ID, Twitch username, Kick numeric broadcaster ID or subreddit name');}
 }}return next;
}
const locks=new Set();
async function exclusive(key,fn){if(locks.has(key))throw Error('An operation is already running. Please retry.');locks.add(key);try{return await fn();}finally{locks.delete(key);}}
export async function publishPanel(g,kind){const cfg=community(g.id)[kind];if(!cfg?.enabled)throw Error('Enable and save this module first');const channel=textChannel(g,cfg.channelId);
 if(kind==='tickets')return publishTicketPanel(g,channel);
 let components;
 if(kind==='selfroles'){for(const id of cfg.roleIds)safeRole(g,id);components=[new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId('vex:roles:select').setPlaceholder('Choose your roles').setMinValues(0).setMaxValues(cfg.exclusive?1:cfg.roleIds.length).addOptions(cfg.roleIds.map(id=>({label:g.roles.cache.get(id).name.slice(0,100),value:id}))))];}
 else if(kind==='embeds')components=[];else throw Error('Unknown panel');
 const message=await channel.send(card(g.id,cfg.title,cfg.message,{components}));event(g.id,'panel_published',{kind,channel:channel.id,message:message.id});return {url:message.url};
}
const moderationPerm={warn:P.ModerateMembers,timeout:P.ModerateMembers,untimeout:P.ModerateMembers,kick:P.KickMembers,ban:P.BanMembers,unban:P.BanMembers,clear:P.ManageMessages};
export async function moderate(g,actor,{action,target,reason='No reason supplied',minutes=10,amount=10,channel}){
 if(!community(g.id).moderation.enabled)throw Error('Moderation is disabled');const permission=moderationPerm[action];if(!permission||!actor.permissions.has(permission))throw Error('Missing moderation permission');if(!g.members.me?.permissions.has(permission)&&action!=='warn')throw Error('VEX is missing the required permission');reason=String(reason).slice(0,450);
 if(action==='clear'){const c=textChannel(g,channel);if(!c.permissionsFor(actor)?.has(P.ManageMessages)||!c.permissionsFor(g.members.me)?.has(P.ManageMessages))throw Error('Manage Messages required for you and VEX in this channel');if(!Number.isInteger(amount)||amount<1||amount>100)throw Error('Choose 1–100 messages');const deleted=await c.bulkDelete(amount,true);const id=addCase(g.id,actor.id,channel,action,reason);return {id,result:`${deleted.size} recent messages removed. Messages older than 14 days are skipped.`};}
 if(!/^\d{17,22}$/.test(target||''))throw Error('Invalid member ID');
 if(action!=='unban'){const m=await g.members.fetch({user:target,force:true});if(m.id===g.ownerId||m.id===actor.id||m.id===g.members.me.id||actor.id!==g.ownerId&&actor.roles.highest.comparePositionTo(m.roles.highest)<=0)throw Error('You cannot moderate this member');
 if(action==='timeout'){if(!m.moderatable||!Number.isInteger(minutes)||minutes<1||minutes>40320)throw Error('Invalid timeout or role hierarchy');await m.timeout(minutes*60000,reason);}
 if(action==='untimeout'){if(!m.moderatable)throw Error('VEX cannot moderate this member');await m.timeout(null,reason);}
 if(action==='kick'){if(!m.kickable)throw Error('VEX cannot kick this member');await m.kick(reason);}
 if(action==='ban'){if(!m.bannable)throw Error('VEX cannot ban this member');await m.ban({reason});}
 }else await g.bans.remove(target,reason);
 const id=addCase(g.id,actor.id,target,action,reason);return {id,result:`${action} · <@${target}>\n${reason}`};
}
export const communityCommandNames=new Set(['welcome','rank','leaderboard','roles','ticket','room','invite','moderate','cases']);
export async function communityInteraction(i){
 if(await handleTicketInteraction(i))return true;
 if(i.isStringSelectMenu()&&i.customId==='vex:roles:select'){await deferPrivate(i);try{const cfg=community(i.guildId).selfroles;if(!cfg.enabled)throw Error('Self roles are disabled');if(i.values.some(id=>!cfg.roleIds.includes(id))||cfg.exclusive&&i.values.length>1)throw Error('This menu is outdated. Open a new role menu.');const m=await i.guild.members.fetch({user:i.user.id,force:true});if(i.customId==='vex:roles:select'){const {checkComponentAccess}=await import('./interaction-response.js');await checkComponentAccess(i,m,'roles');}for(const id of cfg.roleIds)safeRole(i.guild,id);const remove=cfg.roleIds.filter(id=>m.roles.cache.has(id)&&!i.values.includes(id)),add=i.values.filter(id=>!m.roles.cache.has(id));for(const id of remove)await m.roles.remove(id,'VEX self role');for(const id of add)await m.roles.add(id,'VEX self role');await i.editReply(card(i.guildId,'Your roles are updated',i.values.map(id=>`<@&${id}>`).join(' · ')||'No optional roles selected.'));}catch(e){await i.editReply(card(i.guildId,'Could not update roles',e.message));}return true;}
 if(!i.isChatInputCommand()||!communityCommandNames.has(i.commandName))return false;
 await deferPrivate(i);try{const g=i.guild,c=community(g.id),name=i.commandName;let output;
 if(name==='welcome'){const actor=await g.members.fetch({user:i.user.id,force:true});if(!actor.permissions.has(P.ManageGuild))throw Error('Manage Server permission required');const action=i.options.getSubcommand();if(action==='configure'){const {canEdit,saveVersion}=await import('./workspace.js');if(!canEdit(g,actor,'community'))throw Error('Community editing access required');const patch={};const enabled=i.options.getBoolean('enabled'),channel=i.options.getChannel('channel'),message=i.options.getString('message');if(enabled!==null)patch.enabled=enabled;if(channel)patch.channelId=channel.id;if(message!==null)patch.message=message;checkCommunity(g,{welcome:patch});saveVersion(g.id,{community:{welcome:patch}},actor.id);output=card(g.id,'Welcome settings saved','Your dashboard and bot now use the same settings.');}else if(action==='preview')output=memberCard(g,c.welcome,actor);else output=card(g.id,'Welcome studio',`**Status:** ${c.welcome.enabled?'Enabled':'Disabled'}\n**Channel:** ${c.welcome.channelId?'<#'+c.welcome.channelId+'>':'Not configured'}\n**Format:** ${c.welcome.format}\n**Private copy:** ${c.welcome.privateCopy?'On':'Off'}\n\nCustomize the design, message, information blocks and links in your dashboard.`,{components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setLabel('Open Welcome studio').setStyle(ButtonStyle.Link).setURL(env.publicUrl))]});}
 if(name==='community')output=card(g.id,'VEX · Your community hub','**Explore**\n`/server` · `/member` · `/avatar` · `/ping`\n\n**Participate**\n`/rank` · `/leaderboard` · `/roles` · `/ticket`\n\n**Your space**\n`/room` · `/invite`\n\n**Team tools**\n`/moderate` · `/cases`\n\nEnable and personalize modules in the dashboard.',{components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setLabel('Open control center').setStyle(ButtonStyle.Link).setURL(env.publicUrl))]});
 if(name==='ping')output=card(g.id,'Connection pulse',`${Math.max(0,Math.round(i.client.ws.ping))} ms gateway latency`);
 if(name==='server')output=card(g.id,g.name,`**Members** ${g.memberCount}\n**Channels** ${g.channels.cache.size}\n**Roles** ${g.roles.cache.size}\n**Created** <t:${Math.floor(g.createdTimestamp/1000)}:D>`);
 if(name==='member'||name==='avatar'){const u=i.options.getUser('member')||i.user,m=await g.members.fetch(u.id);output=card(g.id,u.username,`**Joined** <t:${Math.floor(m.joinedTimestamp/1000)}:D>\n**Account created** <t:${Math.floor(u.createdTimestamp/1000)}:D>`);if(name==='avatar')output.embeds[0].setImage(u.displayAvatarURL({size:1024}));else output.embeds[0].setThumbnail(u.displayAvatarURL());}
 if(name==='rank'){if(!c.levels.enabled)throw Error('Leveling is disabled');const u=i.options.getUser('member')||i.user,r=rank(g.id,u.id),next=100*(r.level+1)**2,progress=Math.floor((r.xp-100*r.level**2)/(next-100*r.level**2)*10);output=card(g.id,`${u.username} · Level ${r.level}`,`${'▰'.repeat(progress)}${'▱'.repeat(10-progress)}\n**${r.xp} XP** · ${next-r.xp} XP to next level\nPosition **#${r.position}**`);output.embeds[0].setThumbnail(u.displayAvatarURL());}
 if(name==='leaderboard'){if(!c.levels.enabled)throw Error('Leveling is disabled');output=card(g.id,'Community leaderboard',leaderboard(g.id).slice(0,10).map((r,n)=>`**${n+1}.** <@${r.user}> · Level ${r.level} · ${r.xp} XP`).join('\n')||'Your story starts with the first message.');}
 if(name==='roles'){if(!c.selfroles.enabled)throw Error('Self roles are disabled');const cfg=c.selfroles;for(const id of cfg.roleIds)safeRole(g,id);output=card(g.id,cfg.title,cfg.message,{components:[new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId('vex:roles:select').setPlaceholder('Choose your roles').setMinValues(0).setMaxValues(cfg.exclusive?1:cfg.roleIds.length).addOptions(cfg.roleIds.map(id=>({label:g.roles.cache.get(id).name.slice(0,100),value:id}))))]});}
 if(name==='invite'){if(!c.templinks.enabled)throw Error('Temporary invites are disabled');const actor=await g.members.fetch({user:i.user.id,force:true});if(!actor.permissions.has(P.CreateInstantInvite))throw Error('Create Invite permission required');const ch=g.channels.cache.get(c.templinks.channelId);if(!ch?.permissionsFor(actor)?.has(P.CreateInstantInvite))throw Error('Create Invite required in destination channel');const link=await ch.createInvite({maxAge:c.templinks.hours*3600,maxUses:c.templinks.uses,unique:true,reason:'VEX invite requested by '+i.user.id});output=card(g.id,'Your limited invitation',`${link.url}\nExpires in ${c.templinks.hours} hours · ${c.templinks.uses} uses`);}
 if(name==='room'){if(!c.tempvoice.enabled)throw Error('Temporary voice is disabled');const m=await g.members.fetch({user:i.user.id,force:true}),ch=m.voice.channel,owned=getState(g.id,'tempvoice',{});if(!ch||owned[ch.id]!==m.id)throw Error('Join your own VEX temporary room first');const action=i.options.getString('action',true);if(action==='rename')await ch.setName((i.options.getString('name')||m.user.username+' room').slice(0,80));if(action==='lock'||action==='unlock'){if(action==='lock')await ch.permissionOverwrites.edit(m.id,{Connect:true});await ch.permissionOverwrites.edit(g.id,{Connect:action==='lock'?false:null});}output=card(g.id,'Room updated',`<#${ch.id}> · ${action}`);}
 if(name==='moderate'){const actor=await g.members.fetch({user:i.user.id,force:true});const result=await moderate(g,actor,{action:i.options.getString('action',true),target:i.options.getString('member_id'),reason:i.options.getString('reason')||undefined,minutes:i.options.getInteger('minutes')??10,amount:i.options.getInteger('amount')??10,channel:i.channelId});output=card(g.id,'Case #'+result.id,result.result);}
 if(name==='cases'){const actor=await g.members.fetch({user:i.user.id,force:true});if(!actor.permissions.has(P.ModerateMembers))throw Error('Moderate Members required');output=card(g.id,'Moderation casebook',cases(g.id).slice(0,10).map(r=>`**#${r.id} · ${r.action}** <@${r.target}>\n${r.reason}`).join('\n\n')||'No moderation cases yet.');}
 await i.editReply(output||card(g.id,'VEX','Open `/commands` to explore.'));
 }catch(e){await i.editReply(card(i.guildId,'Action could not be completed',e.message)).catch(()=>{});}return true;
}
const cooldowns=new Map();
function cooldown(key,seconds){const now=Date.now();if((cooldowns.get(key)||0)>now)return false;if(cooldowns.size>10000)for(const[k,v]of cooldowns)if(v<now)cooldowns.delete(k);if(cooldowns.size>20000)return false;cooldowns.set(key,now+seconds*1000);return true;}
export function attachCommunity(client){
 attachTicketRefresh(client);
 const on=(type,fn)=>client.on(type,(...args)=>void Promise.resolve().then(()=>fn(...args)).catch(e=>{console.warn('Community event failed:',type,e.code||e.name);}));
 on(Events.GuildMemberAdd,async m=>{const c=community(m.guild.id);if(m.user.bot){if(c.welcome.enabled&&c.welcome.includeBots)await textChannel(m.guild,c.welcome.channelId).send(memberCard(m.guild,c.welcome,m));return;}if(c.statistics.enabled)count(m.guild.id,'joins');if(c.autoroles.enabled)for(const id of c.autoroles.roleIds){try{safeRole(m.guild,id);await m.roles.add(id,'VEX auto role');}catch(e){event(m.guild.id,'autorole_failed',{member:m.id,role:id,result:'Check role hierarchy and permissions'});}}if(c.welcome.enabled){const payload=memberCard(m.guild,c.welcome,m);try{await textChannel(m.guild,c.welcome.channelId).send(payload);}catch{event(m.guild.id,'welcome_delivery_failed',{member:m.id,destination:'channel'});}if(c.welcome.privateCopy)try{await m.send(payload);}catch{event(m.guild.id,'welcome_delivery_failed',{member:m.id,destination:'dm'});}}});
 on(Events.GuildMemberRemove,async m=>{if(m.user.bot)return;const c=community(m.guild.id);if(c.statistics.enabled)count(m.guild.id,'leaves');if(c.goodbye.enabled)await textChannel(m.guild,c.goodbye.channelId).send(memberCard(m.guild,c.goodbye,m));});
 on(Events.MessageCreate,async m=>{if(!m.guild||m.author.bot||m.webhookId)return;const c=community(m.guild.id);if(c.statistics.enabled)count(m.guild.id,'messages');
 if(c.levels.enabled){const r=awardXP(m.guild.id,m.author.id,m.content,c.levels.xp,c.levels.cooldown);if(r&&r.level>r.previous){if(c.levels.channelId)await textChannel(m.guild,c.levels.channelId).send(card(m.guild.id,'A new milestone',`<@${m.author.id}> reached **Level ${r.level}** · ${r.xp} XP`));for(const reward of c.levels.rewards)if(reward.level<=r.level&&reward.roleId){safeRole(m.guild,reward.roleId);await m.member.roles.add(reward.roleId,'VEX level reward');}}}
 if(c.responder.enabled){for(const [n,r]of c.responder.rules.entries()){if(r.channelId&&r.channelId!==m.channelId)continue;const source=m.content.toLowerCase(),trigger=r.trigger.toLowerCase();if(trigger&&(r.match==='exact'?source===trigger:source.includes(trigger))&&cooldown(`${m.guildId}:${m.author.id}:${n}`,c.responder.cooldown)){await m.reply(card(m.guild.id,'VEX · Quick reply',template(r.response,m.member)));break;}}}
 });
 const star=async(reaction,user)=>{if(user.bot)return;if(reaction.partial)await reaction.fetch();const m=reaction.message.partial?await reaction.message.fetch():reaction.message;if(!m.guild||m.author?.bot||m.author?.id===user.id)return;const cfg=community(m.guild.id).starboard;if(!cfg.enabled||reaction.emoji.name!=='⭐'||m.channelId===cfg.channelId)return;
 await exclusive(m.guildId+':star:'+m.id,async()=>{const users=await reaction.users.fetch({limit:100}),stars=users.filter(u=>!u.bot&&u.id!==m.author.id).size,key='star:'+m.id,posted=getState(m.guildId,key);if(stars<cfg.threshold&&!posted)return;const dest=textChannel(m.guild,cfg.channelId);if(!dest.permissionsFor(m.guild.roles.everyone)?.has(P.ViewChannel)||!m.channel.permissionsFor(m.guild.roles.everyone)?.has(P.ViewChannel))return;
 const payload=card(m.guildId,`⭐ ${stars} · Community spotlight`,`${m.content.slice(0,1700)||'A community moment'}\n\n[View original message](${m.url})\nBy <@${m.author.id}>`);if(posted){const old=await dest.messages.fetch(posted).catch(()=>null);if(old){if(stars<cfg.threshold){await old.delete();setState(m.guildId,key,null);}else await old.edit(payload);return;}}
 if(stars>=cfg.threshold){const out=await dest.send(payload);setState(m.guildId,key,out.id);}});
 };on(Events.MessageReactionAdd,star);on(Events.MessageReactionRemove,star);
 on(Events.VoiceStateUpdate,async(before,after)=>{const g=after.guild,cfg=community(g.id).tempvoice;let owned=getState(g.id,'tempvoice',{});
 if(before.channelId&&owned[before.channelId]){const old=g.channels.cache.get(before.channelId);if(old&&old.members.size===0){await old.delete('VEX empty temporary room');owned=getState(g.id,'tempvoice',{});delete owned[before.channelId];setState(g.id,'tempvoice',owned);}}
 if(!cfg.enabled||after.channelId!==cfg.lobbyId||before.channelId===after.channelId||after.member.user.bot)return;
 await exclusive(g.id+':room:'+after.id,async()=>{if(!cooldown(g.id+':roomcreate:'+after.id,20))return;owned=getState(g.id,'tempvoice',{});const existing=Object.keys(owned).find(id=>owned[id]===after.id&&g.channels.cache.has(id));if(existing){await after.setChannel(existing);return;}
 const ch=await g.channels.create({name:template(cfg.name,after.member),type:ChannelType.GuildVoice,parent:cfg.categoryId,userLimit:cfg.limit,reason:'VEX personal voice room'});owned=getState(g.id,'tempvoice',{});owned[ch.id]=after.id;setState(g.id,'tempvoice',owned);try{await after.setChannel(ch);}catch(e){await ch.delete('VEX failed voice move').catch(()=>{});delete owned[ch.id];setState(g.id,'tempvoice',owned);throw e;}});
 });
 on(Events.ClientReady,async()=>{for(const g of client.guilds.cache.values()){const owned=getState(g.id,'tempvoice',{});for(const id of Object.keys(owned)){const ch=g.channels.cache.get(id);if(!ch){delete owned[id];continue;}if(ch.members.size===0){await ch.delete('VEX empty room recovery').catch(()=>{});if(!g.channels.cache.has(id))delete owned[id];}}setState(g.id,'tempvoice',owned);}});
}
export const communitySummary=g=>({daily:daily(g),leaderboard:leaderboard(g),cases:cases(g),tickets:tickets(g)});
