import {installSecuritySuite} from './security-suite-runtime.js';
import {installCommandRuntime} from './command-runtime.js';
import {installExperienceRuntime} from './experience-runtime.js';
import {installGiftRuntime} from './gift-runtime.js';
import {installProductRuntime} from './product-runtime.js';
import {validateEnv} from './config.js';
import {installTicketJourney} from './ticket-bootstrap.js';
validateEnv();
installTicketJourney();
installCommandRuntime();
installGiftRuntime();
installExperienceRuntime();
installProductRuntime();
installSecuritySuite();
const {startWeb}=await import('./web.js');
const {client,startBot}=await import('./bot.js');
// These are bounded, once-only lifecycle hooks for the installed integrations.
client.setMaxListeners(Math.max(client.getMaxListeners(),20));
const {attachTicketRefresh,attachTicketInteractions}=await import('./tickets.js');
attachTicketRefresh(client);
attachTicketInteractions(client);
const {attachCommandCore}=await import('./command-core.js');
attachCommandCore(client);
const {attachWelcomeJourney}=await import('./welcome-journey.js');
const {attachLogCommands}=await import('./log-commands.js');
attachWelcomeJourney(client);
attachLogCommands(client);
const {attachExperienceAudit}=await import('./experience-audit.js');
attachExperienceAudit(client);
const {attachCommandExperience}=await import('./command-experience.js');
attachCommandExperience(client);
const {auditSubscriptionIsolation}=await import('./subscription-diagnostics.js');
auditSubscriptionIsolation();
const {attachTierBranding}=await import('./tier-branding.js');
attachTierBranding(client);
const {attachFeatureGate}=await import('./feature-policy.js');
const {attachAutomations}=await import('./automations.js');
attachFeatureGate(client);
attachAutomations(client);
const {attachProductAudit}=await import('./product-audit.js');
attachProductAudit(client);
startWeb();
startBot().catch(e=>{console.error('Bot login failed:',e);process.exit(1);});
