import {installCommandRuntime} from './command-runtime.js';
import {installExperienceRuntime} from './experience-runtime.js';
import {installGiftRuntime} from './gift-runtime.js';
import {validateEnv} from './config.js';
import {installTicketJourney} from './ticket-bootstrap.js';
validateEnv();
installTicketJourney();
installCommandRuntime();
installGiftRuntime();
installExperienceRuntime();
const {startWeb}=await import('./web.js');
const {client,startBot}=await import('./bot.js');
const {attachTicketRefresh,attachTicketInteractions}=await import('./tickets.js');
attachTicketRefresh(client);
attachTicketInteractions(client);
const {attachCommandCore}=await import('./command-core.js');
attachCommandCore(client);
const {attachWelcomeJourney}=await import('./welcome-journey.js');
const {attachLogCommands}=await import('./log-commands.js');
attachWelcomeJourney(client);
attachLogCommands(client);
const {attachExperienceAudit}=await import('./experience-audit.js');
attachExperienceAudit(client);
startWeb();
startBot().catch(e=>{console.error('Bot login failed:',e);process.exit(1);});
