import {settings,getState,setState,event} from './db.js';
import {card} from './community.js';
const requirements={youtube:['YOUTUBE_API_KEY'],twitch:['TWITCH_CLIENT_ID','TWITCH_CLIENT_SECRET'],kick:['KICK_CLIENT_ID','KICK_CLIENT_SECRET'],reddit:['REDDIT_CLIENT_ID','REDDIT_CLIENT_SECRET','REDDIT_REFRESH_TOKEN']};
const tokens=new Map(),playlists=new Map();
const ready=p=>requirements[p].every(k=>!!process.env[k]);
export const notificationStatus=g=>Object.entries(requirements).map(([provider,keys])=>({provider,configured:ready(provider),missing:keys.filter(k=>!process.env[k]),...(getState(g,'notify-status:'+provider)||{})}));
async function json(url,options={}){const r=await fetch(url,{...options,redirect:'error',signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error('Provider HTTP '+r.status);return r.json();}
async function token(provider){const cached=tokens.get(provider);if(cached&&cached.until>Date.now())return cached.value;const prefix=provider.toUpperCase(),body=new URLSearchParams({grant_type:provider==='reddit'?'refresh_token':'client_credentials'}),headers={'content-type':'application/x-www-form-urlencoded'};
 if(provider==='reddit'){body.set('refresh_token',process.env.REDDIT_REFRESH_TOKEN);headers.Authorization='Basic '+Buffer.from(process.env.REDDIT_CLIENT_ID+':'+process.env.REDDIT_CLIENT_SECRET).toString('base64');headers['User-Agent']='VEXCommunity/3.0';}else{body.set('client_id',process.env[prefix+'_CLIENT_ID']);body.set('client_secret',process.env[prefix+'_CLIENT_SECRET']);}
 const url={twitch:'https://id.twitch.tv/oauth2/token',kick:'https://id.kick.com/oauth/token',reddit:'https://www.reddit.com/api/v1/access_token'}[provider],r=await json(url,{method:'POST',body,headers});if(!r.access_token)throw Error('Provider authorization failed');tokens.set(provider,{value:r.access_token,until:Date.now()+Math.min(Math.max(60,(r.expires_in||3600)-60),3600)*1000});return r.access_token;
}
export async function fetchItems(feed){const {provider:p,source:s}=feed;
 if(p==='youtube'){const query=async(path,params)=>json('https://www.googleapis.com/youtube/v3/'+path+'?'+new URLSearchParams({...params,key:process.env.YOUTUBE_API_KEY}));let playlist=playlists.get(s);if(!playlist){const r=await query('channels',{part:'contentDetails',id:s});playlist=r.items?.[0]?.contentDetails?.relatedPlaylists?.uploads;if(!playlist)throw Error('YouTube channel not found');playlists.set(s,playlist);}const r=await query('playlistItems',{part:'snippet',playlistId:playlist,maxResults:'5'});return (r.items||[]).map(x=>({id:x.snippet.resourceId.videoId,title:x.snippet.title,url:'https://www.youtube.com/watch?v='+x.snippet.resourceId.videoId}));}
 const bearer=await token(p);
 if(p==='twitch'){const r=await json('https://api.twitch.tv/helix/streams?'+new URLSearchParams({user_login:s}),{headers:{Authorization:'Bearer '+bearer,'Client-Id':process.env.TWITCH_CLIENT_ID}});return (r.data||[]).map(x=>({id:x.id,title:x.user_name+' is live · '+x.title,url:'https://www.twitch.tv/'+encodeURIComponent(s)}));}
 if(p==='kick'){const r=await json('https://api.kick.com/public/v1/users/livestreams?'+new URLSearchParams({user_id:s}),{headers:{Authorization:'Bearer '+bearer}});return (r.data||[]).map(x=>({id:x.id,title:x.broadcaster_user?.username+' is live · '+x.title,url:'https://kick.com/'+encodeURIComponent(x.channel.slug)}));}
 const r=await json('https://oauth.reddit.com/r/'+encodeURIComponent(s)+'/new?limit=5&raw_json=1',{headers:{Authorization:'Bearer '+bearer,'User-Agent':'VEXCommunity/3.0'}});return (r.data?.children||[]).filter(x=>!x.data.over_18).map(({data:x})=>({id:x.id,title:x.title,url:'https://www.reddit.com'+x.permalink}));
}
// First successful fetch establishes a baseline; existing content is never dumped into a channel.
export async function deliverFeed(g,feed,items){const key='notify:'+feed.provider+':'+feed.source+':'+feed.channelId,previous=getState(g.id,key);const ids=items.map(i=>String(i.id));if(!previous){setState(g.id,key,ids);return 0;}const seen=new Set(previous);let sent=0;for(const item of [...items].reverse()){if(seen.has(String(item.id)))continue;const c=g.channels.cache.get(feed.channelId);if(!c||![0,5].includes(c.type)||!c.permissionsFor(g.members.me)?.has(['ViewChannel','SendMessages','EmbedLinks']))throw Error('Announcement channel unavailable');await c.send(card(g.id,item.title,'[Watch / read]('+item.url+')'));seen.add(String(item.id));setState(g.id,key,[...seen].slice(-100));sent++;}setState(g.id,key,[...new Set([...previous,...ids])].slice(-100));return sent;}
let timer,running=false;
export function startNotifications(client){if(timer)return;const poll=async()=>{if(running||!client.isReady())return;running=true;const cache=new Map();try{for(const g of client.guilds.cache.values()){const cfg=settings(g.id).community.notifications;if(!cfg.enabled)continue;for(const feed of cfg.feeds){if(!ready(feed.provider))continue;try{const key=feed.provider+':'+feed.source;if(!cache.has(key))cache.set(key,await fetchItems(feed));await deliverFeed(g,feed,cache.get(key));setState(g.id,'notify-status:'+feed.provider,{lastSuccess:Date.now(),error:null});}catch(e){tokens.delete(feed.provider);setState(g.id,'notify-status:'+feed.provider,{error:String(e.message).slice(0,100),lastAttempt:Date.now()});event(g.id,'notification_failed',{provider:feed.provider,result:'Delivery deferred; check provider connection and channel permissions'});}}}}finally{running=false;}};void poll();timer=setInterval(()=>void poll(),600000);timer.unref();}
