import {db,settings,saveSettings,getState,setState} from './db.js';
import {PermissionFlagsBits as P} from 'discord.js';
import {commandDefaults} from './command-policy.js';
export const scopes=['community','protection','logs','moderation','publishing'];
db.exec(`CREATE TABLE IF NOT EXISTS dashboard_history(id INTEGER PRIMARY KEY AUTOINCREMENT,guild TEXT NOT NULL,actor TEXT NOT NULL,at INTEGER NOT NULL,summary TEXT NOT NULL,previous TEXT NOT NULL); CREATE INDEX IF NOT EXISTS dashboard_history_guild ON dashboard_history(guild,id);`);
export const accessPolicy=g=>getState(g,'dashboard_access',{});
export function canEdit(g,m,scope){if(m.id===g.ownerId)return true;if(!m.permissions.has(P.Administrator))return false;const entry=accessPolicy(g.id)[m.id];return entry===undefined||entry.includes(scope);}
export function patchScopes(p){return [...new Set(Object.keys(p).map(k=>k==='community'?'community':k==='commandRules'?'moderation':k==='activityLogs'||k==='logsChannelId'?'logs':'protection'))];}
export function validateAccess(value){if(!value||typeof value!=='object'||Array.isArray(value)||Object.keys(value).length>50)throw Error('Invalid access policy');const out={};for(const[id,list]of Object.entries(value)){if(!/^\d{17,22}$/.test(id)||!Array.isArray(list)||list.some(x=>!scopes.includes(x)))throw Error('Invalid access policy');out[id]=[...new Set(list)];}return out;}
export const history=g=>db.prepare('SELECT id,actor,at,summary FROM dashboard_history WHERE guild=? ORDER BY id DESC LIMIT 30').all(g);
export const revision=(g,id)=>db.prepare('SELECT * FROM dashboard_history WHERE guild=? AND id=?').get(g,id);
export function saveVersion(g,p,actor){return db.transaction(()=>{const old=settings(g),previous={};for(const[k,v]of Object.entries(p)){previous[k]=['community','modules','activityLogs','commandRules'].includes(k)?Object.fromEntries(Object.keys(v).map(id=>[id,k==='commandRules'?{...commandDefaults(),...old[k][id]}:old[k][id]])):old[k];}const result=saveSettings(g,p);if(Object.keys(p).length){db.prepare('INSERT INTO dashboard_history(guild,actor,at,summary,previous) VALUES(?,?,?,?,?)').run(g,actor,Date.now(),Object.entries(p).map(([k,v])=>['community','modules','activityLogs','commandRules'].includes(k)?Object.keys(v).join(', '):k).join(' · ').slice(0,500),JSON.stringify(previous));db.prepare('DELETE FROM dashboard_history WHERE guild=? AND id NOT IN (SELECT id FROM dashboard_history WHERE guild=? ORDER BY id DESC LIMIT 30)').run(g,g);}return result;})();}
export const preferences=(g,u)=>getState(g,'dashboard_pref:'+u,{theme:'violet',favorites:[],readAt:0});
export function savePreferences(g,u,p){const out={...preferences(g,u)};if('theme'in p){if(!['violet','midnight','gold'].includes(p.theme))throw Error('Invalid theme');out.theme=p.theme;}if('favorites'in p){if(!Array.isArray(p.favorites)||p.favorites.length>20||p.favorites.some(x=>typeof x!=='string'||!/^([a-z]+|community:[a-z]+|module:[a-z]+)$/.test(x)))throw Error('Invalid favorites');out.favorites=[...new Set(p.favorites)];}if('readAt'in p){if(!Number.isSafeInteger(p.readAt)||p.readAt<0||p.readAt>Date.now()+5000)throw Error('Invalid read time');out.readAt=p.readAt;}setState(g,'dashboard_pref:'+u,out);return out;}
